# Numpy ufuncs

In [1]:
import numpy as np

## 0_ufuncs intro

In [5]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
z = []
# how to add up these two lists?
for i, j in zip(x, y):
    z.append(i + j)
print(z)

# numpy method 
z = np.add(x, y)
print(z)

[6, 8, 10, 12]
[ 6  8 10 12]


# 1_Create Your Own ufunc

- frompyfunc(function, inputs, outputs)  
    - function - the name of the function  
    - inputs - the number of input arguments  
    - outputs - the number of output arrays  

In [6]:
def myadd(x, y):
    return x + y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


## check if a Function is a ufunc

In [7]:
print(type(np.add))

<class 'numpy.ufunc'>


In [8]:
print(type(np.concatenate))

<class 'function'>


In [9]:
if type(np.add) == np.ufunc:
    print('Yes')
else:
    print('No')

Yes


# 2_Simple Arithmetic

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
newarr = np.add(arr1, arr2)
print(newarr)
newarr = np.subtract(arr1, arr2)
print(newarr)
newarr = np.multiply(arr1, arr2)
print(newarr)
newarr = np.divide(arr1, arr2)
print(newarr)
newarr = np.power(arr1, arr2)
print(newarr)
newarr = np.mod(arr2, arr1)
print(newarr)
newarr = np.divmod(arr2, arr1)
print(newarr)
arr = np.array([-1,-2,-3,-4,-5])
newarr = np.absolute(arr)
print(newarr)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[0 1 2 1 0]
(array([6, 3, 2, 2, 2]), array([0, 1, 2, 1, 0]))
[1 2 3 4 5]


# 3_Rounding Decimals

- truncation
- fix 
- rounding
- floor
- ceil

## Truncation

In [22]:
arr = np.array([-3.166, 3.667])
print(np.trunc(arr))
print(np.fix(arr)) # they are not the same but the results are the same

[-3.  3.]
[-3.  3.]


## Rounding 

In [ ]:
print(np.around(3.166, 2)) # 四舍五入保留几位小数

3.17


In [35]:
arr = np.array([-3.166,3.667])
print(np.floor(arr)) # 往负无穷取整
print(np.ceil(arr)) # 往正无穷取整

[-4.  3.]
[-3.  4.]


# 4_NumPy Logs

- base 2
- base e 
- base 10
- base any

In [42]:
arr = np.arange(1,10)
print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))

from math import log
nplog = np.frompyfunc(log,2,1)
print(nplog(100, 15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


# 5_NumPy Summations

- difference between summantion and addition?
    - addition: between 2 arguments 
    - summation: between n arguments

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.add(arr1, arr2)
print(newarr)
newarr = np.sum([arr1, arr2])
print(newarr)

[5 7 9]
21


## sum over an axis

In [46]:
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[ 6 15]


## Cummulative Sum

In [48]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


# 6_NumPy Products 

In [49]:
arr = np.array([1,2,3,4])
x = np.prod(arr)
print(x)

24


In [53]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.prod([arr1, arr2])
print(arr)
arr = np.prod([arr1, arr2], axis=1)
print(arr)
arr = np.cumprod(arr1)
print(arr)

40320
[  24 1680]
[ 1  2  6 24]


# 7_NumPy Differences

In [55]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)
newarr = np.diff(arr, n=2) # do once more
print(newarr)

[  5  10 -20]
[  5 -30]


# 8_NumPy LCM Lowest Common Multiple

## LCM of numbers

In [58]:
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(np.lcm(num1, num2)) # 最小公倍数

12


## LCM in an array

In [64]:
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

arr = np.arange(1,11)
print(np.lcm.reduce(arr))

18
2520


# 9_NumPy GCD Greatest Common Devisor

In [ ]:
num1 = 6
num2 = 9
print(np.gcd(num1, num2)) # 最大公约数

3


In [67]:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


# 10_trigonometric Functions

In [68]:
x = np.sin(np.pi / 2)
print(x)

1.0


In [69]:
arr = np.array([np.pi / 2, np.pi /3, np.pi / 4, np.pi / 5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


## Convert Degrees Into Radians 

In [70]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


## Radians to Degrees

In [71]:
arr = np.array([np.pi / 2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


## Finding Angles 

In [80]:
x = np.arcsin(1.0)
print(np.rad2deg(x))
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
x = np.rad2deg(x)
print(x)

90.0
[ 90.         -90.           5.73917048]


## Hypotenues 三角形斜边

In [81]:
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0


# 11_NumPy Hyperbolic Functions 双曲函数

- sinh(x) = $ (e^{x} - e^{-x}) / 2 $
- cosh(x) = $ (e^{x} + e^{-x}) / 2 $
- tanh(x) = sinh(x) / cosh(x) = $ (e^{x} - e^{-x}) / (e^{x} + e^{-x}) $ 

In [82]:
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [85]:
x = np.arcsinh(1.0)
print(x)

0.881373587019543


# 12_NumPy Set Operations 

## Create Sets in NumPy

In [87]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


## Finding Union

In [89]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


## Finding Intersection

In [90]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]



## Finding Difference

In [91]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2]


## Finding Symmetric Difference

In [92]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 5 6]
